sudo: false
os:
- linux
language: haskell
cache:
  directories:
  - "$HOME/.stack"
before_install:
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install cabal-install-3.0
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build
script:
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
- bash make.sh
deploy:
- provider: pages
  local_dir: out
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: false
  on:
    branch: master
env:
  global:
  - secure: ud9AANXLemLkSAWb9wiXFybiQngz6mxDRmZTcyWD9HaoIG0874AaWtJ46dNeUj2LVeup+4dahpy4DvLKrB90FAcNAbcegYVZoEgWiIRt+D0d2z5kCnwJfmaqTODrGRTRb39KtjLfQW9qqFTFIrlL6+8n732AoPMBpXzeWBQgp4V89U7DyflMfo4T10HteSyZ78cfKnZ/KMoi/Bg4jfQO9C7UMZiS/aRgocHFHadXtSMrIHsIFxKzsxTxjo5QzYZNIsINDeu8tyqRFx0uc7W++qAps7XenMCfWtikWHqTcwEI8BWeuhDe+k0DjWJRUv/ofL/JgP8A8W1/U5dLK/onHhtkqJGb/wAx0LiWaA/D4pRxvUgGdmYzArXkZVV8LDfvUsqpnpNwjd44HjBVBHBIqVXdCYwIUDeBpdMcVRNHJ8gQf2z2ITcAZEuf0rC16H1MpzW4ppw5PfjuGQeGWJWXr7m/XP0Bgy7XOVM2QFc6asFtCmf3P87uuOY65Aq69sa3Tr1LcNmLymxeTumSdKJillULpikF13n3NimqW4Rzkd/kKk86dlI04IU73EBnAoDaf18Ep1fmOmyQY0qc15r38S2S+DR2FY1DTNOWJbPn7TWrpzGYHkqZNiShvCDcDG/g8soFtMrvB8sOCgFw2p5aYTeMWYDoV8928hlwtH9VBzI=
